using System;
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace K3CloudDataDictionary.Models
{
    public class LocalDataFileInfo : INotifyPropertyChanged
    {
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public long FileSizeBytes { get; set; }
        public DateTime LastModified { get; set; }

        /// <summary>
        /// 关联的连接ID（仅自动生成的文件有此值）
        /// </summary>
        public int? AssociatedConnectionId { get; set; }

        /// <summary>
        /// 关联的连接显示名（含数据库名）
        /// </summary>
        public string AssociatedConnectionName { get; set; }

        /// <summary>
        /// 是否由数据库连接自动生成的本地数据文件（刷新元数据产生）
        /// 自动生成的文件关联不可修改，导入的文件不关联连接
        /// </summary>
        public bool IsAutoGenerated { get; set; }

        private bool _isCurrent;
        /// <summary>
        /// 是否为当前正在使用的本地数据（仅用于 UI 显示）
        /// </summary>
        public bool IsCurrent
        {
            get => _isCurrent;
            set { _isCurrent = value; OnPropertyChanged(); }
        }

        public string DisplayFileSize
        {
            get
            {
                if (FileSizeBytes < 1024) return $"{FileSizeBytes} B";
                if (FileSizeBytes < 1024 * 1024) return $"{FileSizeBytes / 1024.0:F1} KB";
                return $"{FileSizeBytes / (1024.0 * 1024.0):F1} MB";
            }
        }

        public string DisplayName
        {
            get
            {
                if (IsAutoGenerated && !string.IsNullOrEmpty(AssociatedConnectionName))
                    return $"{AssociatedConnectionName}";
                return FileName;
            }
        }

        public event PropertyChangedEventHandler PropertyChanged;
        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
    }
}
